{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "nose.failure:Failure", "name": "runTest", "time": 0.00023484230041503906, "type": "error", "errtype": "builtins.SyntaxError", "message": "invalid syntax (index.ipynb, line 168)", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/opt/conda/lib/python3.6/site-packages/nose/failure.py\", line 39, in runTest\n    raise self.exc_val.with_traceback(self.tb)\n  File \"/opt/conda/lib/python3.6/site-packages/nose/loader.py\", line 417, in loadTestsFromName\n    addr.filename, addr.module)\n  File \"/opt/conda/lib/python3.6/site-packages/nose/importer.py\", line 47, in importFromPath\n    return self.importFromDir(dir_path, fqname)\n  File \"/opt/conda/lib/python3.6/site-packages/nose/importer.py\", line 94, in importFromDir\n    mod = load_module(part_fqname, fh, filename, desc)\n  File \"/opt/conda/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/opt/conda/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"<frozen importlib._bootstrap>\", line 684, in _load\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/home/yoyothesheep/calculating-distance-lab-data-science-intro-000/test/index_test.py\", line 2, in <module>\n    from ipynb.fs.full.index import (neighbors,\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 674, in exec_module\n  File \"/opt/conda/lib/python3.6/site-packages/ipynb/fs/full/__init__.py\", line 43, in get_code\n    return self.source_to_code(code_from_ipynb(nb), self.path)\n  File \"/home/yoyothesheep/calculating-distance-lab-data-science-intro-000/index.ipynb\", line 168\n    rl.append(tl.)\n                 ^\nSyntaxError: invalid syntax\n"}]}